steps:
- name: 'gcr.io/cloud-builders/npm'
  args: [ 'install --prefix client' ]
- name: 'gcr.io/cloud-builders/npm'
  args: [ 'run --prefix client', 'build --prefix client' ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--version=1']
  dir: 'client'